# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.TextField(help_text='CarName', verbose_name='CarName')),
                ('weight', models.IntegerField(help_text='Weight', verbose_name='Weight')),
            ],
        ),
    ]
