# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180405_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='car_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Cars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
