# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180405_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_category',
            field=models.IntegerField(default=0, help_text='Category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
