# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_cars_car_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_category_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='cars',
            name='car_category',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_category_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.CarCategory'),
            preserve_default=False,
        ),
    ]
