# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180407_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='car_name',
        ),
        migrations.AddField(
            model_name='event',
            name='car_category_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.CarCategory'),
            preserve_default=False,
        ),
    ]
