# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180407_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='car_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.CarCategory'),
        ),
    ]
