# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180407_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='car_category_name',
            new_name='car_name',
        ),
    ]
