# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20180407_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_category_name',
        ),
    ]
