# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_cars_car_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_category_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.CarCategory'),
            preserve_default=False,
        ),
    ]
